
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: kanban-frontend-prod
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - NODE_ENV=production
    networks:
      - kanban-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"

networks:
  kanban-network:
    driver: bridge 